use std::collections::HashMap;

use super::i18n::I18n;

pub const UI_TEXT_KEYS: &[&str] = &[
    "language.name",
    "gui.done",
    "gui.cancel",
    "gui.none",
    "gui.all",
    "menu.game",
    "menu.singleplayer",
    "menu.multiplayer",
    "menu.options",
    "menu.quit",
    "menu.returnToGame",
    "menu.disconnect",
    "menu.shareToLan",
    "gui.achievements",
    "gui.stats",
    "options.title",
    "options.video",
    "options.videoTitle",
    "options.controls",
    "options.language",
    "options.sounds",
    "options.sounds.title",
    "options.skinCustomisation",
    "options.skinCustomisation.title",
    "options.difficulty",
    "options.difficulty.peaceful",
    "options.difficulty.easy",
    "options.difficulty.normal",
    "options.difficulty.hard",
    "options.guiScale",
    "options.fov",
    "options.fov.min",
    "options.fov.max",
    "options.renderDistance",
    "options.ao",
    "options.ao.off",
    "options.ao.max",
    "options.particles",
    "options.particles.all",
    "options.particles.decreased",
    "options.particles.minimal",
    "options.framerateLimit",
    "options.framerateLimit.max",
    "options.renderClouds",
    "options.entityShadows",
    "options.viewBobbing",
    "options.advancedTooltips",
    "options.betterGrass",
    "options.connectedTextures",
    "options.off",
    "options.on",
    "options.modelPart.cape",
    "options.modelPart.hat",
    "options.modelPart.jacket",
    "options.modelPart.left_sleeve",
    "options.modelPart.right_sleeve",
    "options.modelPart.left_pants_leg",
    "options.modelPart.right_pants_leg",
    "soundCategory.master",
    "soundCategory.music",
    "soundCategory.block",
    "soundCategory.hostile",
    "soundCategory.neutral",
    "soundCategory.player",
    "soundCategory.ambient",
    "soundCategory.weather",
    "soundCategory.ui",
    "container.inventory",
    "container.crafting",
    "controls.title",
    "controls.resetAll",
    "key.forward",
    "key.back",
    "key.left",
    "key.right",
    "key.jump",
    "key.sneak",
    "key.sprint",
    "key.inventory",
    "key.drop",
    "key.hotbar.1",
    "key.hotbar.2",
    "key.hotbar.3",
    "key.hotbar.4",
    "key.hotbar.5",
    "key.hotbar.6",
    "key.hotbar.7",
    "key.hotbar.8",
    "key.hotbar.9",
    "key.chat",
    "key.command",
    "key.playerlist",
    "key.attack",
    "key.use",
    "key.categories.movement",
    "key.categories.gameplay",
    "key.categories.inventory",
    "key.categories.ui",
    "selectServer.title",
    "selectServer.empty",
    "selectServer.select",
    "selectServer.direct",
    "selectServer.delete",
    "selectServer.refresh",
    "addServer.enterIp",
    "addServer.add",
    "deathScreen.title",
    "deathScreen.score",
    "deathScreen.respawn",
    "deathScreen.titleScreen",
    "resourcePack.title",
    "resourcePack.available.title",
    "resourcePack.selected.title",
    "resourcePack.openFolder",
    "resourcePack.folderInfo",
    "multiplayer.texturePrompt.line1",
    "multiplayer.texturePrompt.line2",
    "multiplayer.connecting",
    "multiplayer.loadingWorld",
    "rustcraft.brand",
    "rustcraft.version",
    "rustcraft.multiplayer.user",
    "rustcraft.multiplayer.refreshing",
    "rustcraft.multiplayer.online",
    "rustcraft.multiplayer.offline",
    "rustcraft.multiplayer.unknown",
    "rustcraft.server.join",
    "rustcraft.server.save",
    "rustcraft.language.current",
    "rustcraft.language.reloadNote",
    "rustcraft.audio.nullBackend",
    "rustcraft.resourcePack.accept",
    "rustcraft.resourcePack.decline",
    "rustcraft.resourcePack.status",
    "rustcraft.skin.allCustom",
    "rustcraft.skin.syncNote",
    "rustcraft.controls.pressKey",
    "rustcraft.controls.conflict",
    "rustcraft.weather.rain",
    "rustcraft.weather.thunderstorm",
    "rustcraft.inventory.empty",
    "rustcraft.inventory.crafting",
    "rustcraft.enchant.level",
    "rustcraft.resourcePack.prompt",
    "rustcraft.connection.connecting",
    "rustcraft.connection.connected",
    "rustcraft.connection.disconnected",
    "rustcraft.connection.notConnected",
    "rustcraft.connection.failedWithReason",
    "rustcraft.resourcePack.acceptedPending",
    "rustcraft.resourcePack.declined",
    "rustcraft.resourcePack.offered",
    "rustcraft.server.refreshed",
    "rustcraft.inventory.rejected",
    "rustcraft.inventory.openedWindow",
    "rustcraft.item.unknown",
    "rustcraft.enchant.unknown",
    "options.chat.title",
    "options.chat.width",
    "options.chat.height",
    "options.chat.background",
    "options.chat.overlay",
    "options.chat avatars",
    "options.chat.tabAvatars",
    "rustcraft.modding.title",
    "rustcraft.modding.empty",
    "rustcraft.modding.disconnectTranslator",
    "rustcraft.modding.enable",
    "rustcraft.modding.disable",
    "rustcraft.modding.reload",
    "rustcraft.modding.configure",
    "rustcraft.modding.reloadAll",
    "rustcraft.modding.enabled",
    "rustcraft.modding.disabled",
    "rustcraft.altmanager.title",
    "rustcraft.altmanager.empty",
    "rustcraft.altmanager.addAccount",
    "rustcraft.altmanager.addOffline",
    "rustcraft.altmanager.useAccount",
    "rustcraft.altmanager.remove",
    "rustcraft.altmanager.enterUsername",
    "rustcraft.altmanager.usernameHint",
    "rustcraft.altmanager.confirmHint",
    "rustcraft.modding.inspectPrompt",
    "rustcraft.modding.permissions",
    "rustcraft.modding.running",
    "rustcraft.modding.stopped",
    "rustcraft.modding.protocolTranslator",
    "rustcraft.modding.settings",
    "rustcraft.modding.shortcuts",
    "rustcraft.modding.granted",
    "rustcraft.modding.denied",
];

#[derive(Clone, Debug, Default)]
pub struct UiText {
    values: HashMap<&'static str, String>,
    dynamic_values: HashMap<String, String>,
}

impl UiText {
    pub fn from_i18n(i18n: &I18n) -> Self {
        let values = UI_TEXT_KEYS
            .iter()
            .map(|key| (*key, i18n.t(key)))
            .collect::<HashMap<_, _>>();
        Self {
            values,
            dynamic_values: i18n.merged_translations(),
        }
    }

    pub fn fallback() -> Self {
        let i18n = I18n::load("assets/minecraft/lang/en_US.lang", None);
        Self::from_i18n(&i18n)
    }

    pub fn get(&self, key: &'static str) -> &str {
        self.values.get(key).map(String::as_str).unwrap_or(key)
    }

    pub fn dynamic(&self, key: &str) -> String {
        self.dynamic_values
            .get(key)
            .cloned()
            .unwrap_or_else(|| key.to_string())
    }

    pub fn bool_label(&self, value: bool) -> &str {
        if value {
            self.get("options.on")
        } else {
            self.get("options.off")
        }
    }
}
